var app = angular.module("myapp",['ui.router','ngAnimate','ui.bootstrap']);

app.config(function($stateProvider,$urlRouterProvider){
	$urlRouterProvider.otherwise("/home");

	$stateProvider
		.state('home',{
			url:'/home',
			views:{
				"main":{
					templateUrl:"partials/home.html",
					data:{title:"Home"},
					controller:"HomeController"
				}
			}
		})
		.state('about',{
			url:'/aboutus',
			views:{
				"main":{
					templateUrl:"partials/about.html",
					data:{title:"About"},
					controller:"AboutController"
				}
			}
		})
		.state('contact',{
			url:'/contactus',
			views:{
				"main":{
					templateUrl:"partials/contact.html",
					data:{title:"Contact"},
					controller:"AboutController"
				}
			}
		})
		.state('quality',{
			url:'/quality',
			views:{
				"main":{
					templateUrl:"partials/quality.html",
					data:{title:"Quality"},
					controller:"AboutController"
				}
			}
		});
});